server:
  port: 8081
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://mysql.iishoni.com/boot_crm?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  thymeleaf:
    cache: false
    enabled: false
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.shaw.boot.po
  mapper-locations: classpath:mybatis/mapper/**/*.xml

